
echo "This script will generate all the data for the PSNR section of the paper"
echo "Press ENTER to continue, CTRL+C to stop"
read

python script_create_other_psnr_data_and_msefile.py FRmetricsFrameByFrame.csv mse_000 FRmetricsFrameByFrame_mse.csv

python script_create_psnr_stddev_per_frame.py FRmetricsFrameByFrame.csv FRmetricsFrameByFrame_mse.csv data_psnr000_vs_psnrA00_with_overall_mean_variance.csv

python script_filter_HRCs.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv  list_hrcs_fixedQP.txt data_psnr000_vs_psnrA00_with_overall_mean_variance__fixedQP.csv
python script_filter_HRCs.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv  list_hrcs_RateControl.txt data_psnr000_vs_psnrA00_with_overall_mean_variance__RateControl.csv

python script_compute_perpoint_cdf_function_over_PSNR_G-PSNR_A.py  data_psnr000_vs_psnrA00_with_overall_mean_variance__RateControl.csv  data_psnr000_vs_psnrA00_with_overall_mean_variance__RateControl_cdf.txt
python script_compute_perpoint_cdf_function_over_PSNR_G-PSNR_A.py  data_psnr000_vs_psnrA00_with_overall_mean_variance__fixedQP.csv  data_psnr000_vs_psnrA00_with_overall_mean_variance__fixedQP_cdf.txt




python script_filter_HRCs.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv hrcs_sets/hrcs_content.txt data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_content.csv
python script_filter_HRCs.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv hrcs_sets/hrcs_rd.txt data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_rd.csv
python script_filter_HRCs.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv hrcs_sets/hrcs_random1_97.txt data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_random1_97.csv
python script_filter_HRCs.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv hrcs_sets/hrcs_random2_97.txt data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_random2_97.csv
python script_filter_HRCs.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv hrcs_sets/hrcs_random3_97.txt data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_random3_97.csv
python script_filter_HRCs.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv hrcs_sets/hrcs_random1_83.txt data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_random1_83.csv
python script_filter_HRCs.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv hrcs_sets/hrcs_random2_83.txt data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_random2_83.csv
python script_filter_HRCs.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv hrcs_sets/hrcs_random3_83.txt data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_random3_83.csv


exit
#Compute similarity statistics between graphs
python script_similarity.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_rd.csv > similarity_ALL_with_rd.csv
python script_similarity.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_content.csv > similarity_ALL_with_content.csv

python script_similarity.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_random3_97.csv > similarity_ALL_with_random3_97.csv
python script_similarity.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_random2_97.csv > similarity_ALL_with_random2_97.csv
python script_similarity.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_random1_97.csv > similarity_ALL_with_random1_97.csv

python script_similarity.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_random3_83.csv > similarity_ALL_with_random3_83.csv
python script_similarity.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_random2_83.csv > similarity_ALL_with_random2_83.csv
python script_similarity.py  data_psnr000_vs_psnrA00_with_overall_mean_variance.csv data_psnr000_vs_psnrA00_with_overall_mean_variance__hrcs_random1_83.csv > similarity_ALL_with_random1_83.csv

#Compute similarity table between interpolations
bash command_table_slopes.sh > table_interpolation_comparison.csv

exit
bash command_table_avgdistance_per_src.sh > results_avg_distance_per_point__per_src.txt
bash command_table_avgdistance_per_src.sh > results_avg_tot_distance__per_src.txt


